# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AutoCalculateMathStatement' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AutoCalculateMathStatement
  pod 'Alamofire', '~> 4.8.1'
  pod 'Bond', '~> 7.5.0'
end
